### ISSUE TITLE
consider un-configuring `editor.lineHeight`

### ISSUE THREAD

**Issue by waymondo** [kahole/edamagit#53]
This is really more of a question, but is there a motivation behind configuring the line-height to a fixed size, rather than letting the current theme and global user settings dictate the line-height in magit buffers? I am setting the value to `0` to essentially unset it.

**Comment by kahole** [comment]
This was done to better emulate the default magit experience (the way I perceive it).
By that I mean have as high information density as magit and fit the entire interface.
Of course this is a matter of screen size / resolution / personal preference / etc.

In conclusion; It's like that because to me it feels more like magit that way.

**Comment by waymondo** [comment]
Fair enough, it's not a problem for me to customize

**Comment by kahole** [comment]
This default has now been removed :)
