### ISSUE TITLE
Add Forge?

### ISSUE THREAD

**Issue by nickcernis** [kahole/edamagit#62]
Would you consider implementing (or accepting PRs for) a recreation of [Forge](https://github.com/magit/forge) as part of edamagit?

If we only start with one feature, it would be especially useful to be able to view and checkout PRs:

![687474703a2f2f726561646d652e656d6163736169722e6d652f666f7267652d7374617475732e706e67](https://user-images.githubusercontent.com/647669/88484954-c665c080-cf72-11ea-95e7-7b35be93a5a8.png)

**Comment by kahole** [comment]
I would be open to this for sure.
I’m not all that familiar with Forge. By the looks of it it integrates into Magit by adding extras such as PRs from e.g. github.
An implementation of this into edamagit should be optionally enabled and not interfere otherwise.

Would be great to see a PR on this. :)

**Comment by nickcernis** [comment]
Thanks for your thoughts, @kahole.

I looked into some possible implementation paths.

To reduce the scope the feature could use [GitHub cli](https://github.com/cli/cli) as a backend (which already offers a `gh pr list` and `gh pr checkout` command). This means we wouldn't have to do things like handling GitHub authentication keys or working directly with their GraphQL API. (The user would just need to have `gh` installed and authenticated.)

However, at the moment it likely depends on https://github.com/cli/cli/issues/385 (the `gh` command doesn't output JSON or another easily parsable format yet). I'll keep an eye on that to see when support is added.

**Comment by kahole** [comment]
@nickcernis That sounds like a good way to go about it.

JSON output is probably neater to consume, makes sense ti wait for it. Although, if that doesnt come, parts edamagit parses arbitrarily formatted cl output from git already, so it wouldn't be out of place in this extension 😀

**Comment by nickcernis** [comment]
Hah! I was tempted by that approach, but felt it might be a little more fragile with GitHub CLI being in flux/“early development stages”.

**Comment by stevenguh** [comment]
I am glad that someone bought this up. I think we should take a top down approach instead of a bottom up approach (one vendor specific first) so we can support different forages (e.g. gitlab, gitea) without a lot of rework due to intricacies of using one particular API like gh/cli to start off. However, different vendors offer vastly different API like github offers gh/cli, GraphQL, or REST API. In addition, we might also be able to leverage the upcoming [vscode's authentication provider API](https://github.com/microsoft/vscode/issues/88309) to authenticate a user to use a particular API (thinking private repos).

**Comment by roblabla** [comment]
I think using gh or any other CLI is a pretty bad idea. While it does solve a few issues (such as authentication and locating the forge), it adds a rather unnecessary runtime dependency and will make the whole thing pretty janky. Github has some really solid TypeScript libraries to interact with its APIs (`@octokit/rest.js` and `@octokit/core.js`) that we can leverage instead.

As for the other forges, gitlab has [gitbeaker](https://github.com/jdalrymple/gitbeaker), others we'll probably have to write raw API calls ourselves.

I'll try to take an initial stab at this, initially focusing on github PRs.

**Comment by kahole** [comment]
Initial Forge implemention available in preview.
Turn it on in vscode settings -> magit.

Only github.com forge supporter so far.

**Comment by stevenguh** [comment]
That's awesome 🚀
